Alexa.Skill/Models/Intents/IntentAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentAddViewModel
	{
		[Display(Name = "Session beenden?")]
		public bool ShouldEndSession { get; set; }
		public int SkillId { get; set; }
		[Display(Name = "Intent Name")]
		public string Name { get; set; }

		public IntentAddViewModel()
		{
			ShouldEndSession = true;
		}
	}
}

Alexa.Skill/Models/Intents/IntentDetailViewModel.cs
using Alexa.Skill.Models.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentDetailViewModel
	{
		public int IntentId { get; set; }
		public string Name { get; set; }
		public int SkillId { get; set; }
		public string SkillName { get; set; }

		public List<MessageOverviewItemViewModel> Messages { get; set; }

		public Dictionary<int, string> IntentCalls { get; set; }

		public IntentDetailViewModel()
		{
			Messages = new List<MessageOverviewItemViewModel>();
			IntentCalls = new Dictionary<int, string>();
		}
	}
}

Alexa.Skill/Models/Intents/IntentEditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentEditViewModel
	{
		[Display(Name = "Session beenden?")]
		public bool ShouldEndSession { get; set; }
		public int IntentId { get; set; }
		[Display(Name = "Intent Name")]
		public string Name { get; set; }

		public int SkillId { get; set; }
		public IntentEditViewModel()
		{
			ShouldEndSession = true;
		}
	}
}

Alexa.Skill/Models/Intents/IntentItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Models.Intents
{
	public class IntentItemViewModel
	{
		public int Id { get; set; }

		[AllowHtml]
		public string Name { get; set; }
	}
}

Alexa.Skill/Models/Intents/IntentMessagesOverviewViewModel.cs
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;

namespace Alexa.Skill.Models.Intents
{
	public class IntentMessagesOverviewViewModel
	{
		public int IntentId { get; set; }
		public string IntentName { get; set; }
		public string SkillName { get; set; }

		public List<MessageOverviewItemViewModel> Messages { get; set; }

		public IntentMessagesOverviewViewModel()
		{
			Messages = new List<MessageOverviewItemViewModel>();
		}
	}
}

Alexa.Skill/Models/Intents/IntentOverviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentOverviewViewModel
	{
		public int SkillId { get; set; }
		public List<IntentItemViewModel> Intents { get; set; }

		public IntentOverviewViewModel()
		{
			Intents = new List<IntentItemViewModel>();
		}
	}
}

Alexa.Skill/Controllers/IntentCallController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class IntentCallController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add(int id)
		{
			IntentCallEditViewModel model = new IntentCallEditViewModel()
			{
				IntentId = id
			};
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if (intent != null)
				{
					model.SkillId = intent.SkillId;
				}
			}

			return View("Edit", model);
		}
		#endregion

		#region Edit
		[HttpGet]
		public ActionResult Edit(int id)
		{
			IntentCallEditViewModel model = new IntentCallEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentCall intentCall = db.IntentCalls.FirstOrDefault(x => x.Id == id);
				if (intentCall != null)
				{
					model.IntentCallId = intentCall.Id;
					model.CallText = intentCall.CallText;
					model.IntentId = intentCall.IntentId;
					model.SkillId = intentCall.Intent.SkillId;
				}
			}
			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(IntentCallEditViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				if(model.IntentCallId != 0)
				{
					IntentCall message = db.IntentCalls.FirstOrDefault(x => x.Id == model.IntentCallId);
					if (message != null)
					{
						message.CallText = model.CallText;
					}
				}
				else
				{
					IntentCall intentCall = new IntentCall()
					{
						CallText = model.CallText,
						IntentId = model.IntentId
					};
					db.IntentCalls.Add(intentCall);
				}
				db.SaveChanges();

			}
			return RedirectToAction("Detail", "Intent", new { id = model.IntentId });
		}
		#endregion

		#region Delete
		[HttpGet]
		public ActionResult DeleteConfirm(int id)
		{
			IntentCallEditViewModel model = new IntentCallEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentCall intentCall = db.IntentCalls.FirstOrDefault(x => x.Id == id);
				if (intentCall != null)
				{
					model.IntentCallId = intentCall.Id;
					model.CallText = intentCall.CallText;
					model.IntentId = intentCall.IntentId;
					model.SkillId = intentCall.Intent.SkillId;
				}
			}
			return View(model);
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			IntentCallEditViewModel model = new IntentCallEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentCall intentCall = db.IntentCalls.FirstOrDefault(x => x.Id == id);
				db.IntentCalls.Remove(intentCall);
				db.SaveChanges();
				return RedirectToAction("Detail", "Intent", new { id = intentCall.IntentId });
			}
			
		}
		#endregion
	}
}

Alexa.Skill/Controllers/IntentController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Intents;
using Alexa.Skill.Models.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class IntentController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add(int id)
		{
			IntentAddViewModel model = new IntentAddViewModel()
			{
				SkillId = id
			};


			return View(model);
		}

		[HttpPost]
		public ActionResult Add(IntentAddViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = new Intent()
				{
					SkillId = model.SkillId,
					Name = model.Name.Replace(" ",""),
					ShouldEndSession = model.ShouldEndSession
				};
				db.Intents.Add(intent);
				db.SaveChanges();
				return RedirectToAction("Detail", "Intent", new { id = intent.Id});
			}
		}
		#endregion

		#region Edit
		[HttpGet]
		public ActionResult Edit(int id)
		{
			IntentEditViewModel model = new IntentEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if(intent != null)
				{
					model.IntentId = intent.Id;
					model.Name = intent.Name;
					model.SkillId = intent.SkillId;
					model.ShouldEndSession = intent.ShouldEndSession;
				}
			}
			


			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(IntentEditViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{

				Intent intent = db.Intents.FirstOrDefault(x => x.Id == model.IntentId);
				if (intent != null)
				{
					intent.Name = model.Name;
					intent.ShouldEndSession = model.ShouldEndSession;
				}
				db.SaveChanges();
				return RedirectToAction("Intents", "Skill", new { id = intent.SkillId });
			}
		}
		#endregion

		#region Detail
		public ActionResult Detail(int id)
		{
			IntentDetailViewModel model = new IntentDetailViewModel();
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if(intent == null)
				{
					return null;
				}
				
				model.IntentId = id;
				model.Name = intent.Name;
				model.SkillId = intent.Skill.Id;
				model.SkillName = intent.Skill.Name;

				foreach (IntentMessage message in intent.IntentMessages)
				{
					model.Messages.Add(new MessageOverviewItemViewModel()
					{
						MessageId = message.Id,
						Message = message.Message
					});
				}

				foreach (IntentCall intentCall in intent.IntentCalls)
				{
					model.IntentCalls.Add(intentCall.Id, intentCall.CallText);
				}
			}

			return View(model);
		}
		#endregion
	}
}

Alexa.Skill/Controllers/MessageController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class MessageController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add(int id)
		{
			MessageEditViewModel model = new MessageEditViewModel()
			{
				IntentId = id
			};

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if (intent != null)
				{
					model.SkillId = intent.SkillId;
				}
			}

			return View("Edit", model);
		}
		#endregion

		#region Edit
		[HttpGet]
		public ActionResult Edit(int id)
		{
			MessageEditViewModel model = new MessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentMessage message = db.IntentMessages.FirstOrDefault(x => x.Id == id);
				if (message != null)
				{
					model.MessageId = message.Id;
					model.Message = message.Message;
					model.IntentId = message.IntentId;
					model.SkillId = message.Intent.SkillId;
				}
			}
			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(MessageEditViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				if(model.MessageId != 0)
				{
					IntentMessage message = db.IntentMessages.FirstOrDefault(x => x.Id == model.MessageId);
					if (message != null)
					{
						message.Message = model.Message;
					}
				}
				else
				{
					IntentMessage message = new IntentMessage()
					{
						Message = model.Message,
						IntentId = model.IntentId
					};
					db.IntentMessages.Add(message);
				}
				db.SaveChanges();

			}
			return RedirectToAction("Detail", "Intent", new { id = model.IntentId });
		}
		#endregion

		#region Delete
		[HttpGet]
		public ActionResult DeleteConfirm(int id)
		{
			MessageEditViewModel model = new MessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentMessage message = db.IntentMessages.FirstOrDefault(x => x.Id == id);
				if (message != null)
				{
					model.MessageId = message.Id;
					model.Message = message.Message;
					model.IntentId = message.IntentId;
					model.SkillId = message.Intent.SkillId;
				}
			}
			return View(model);
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			MessageEditViewModel model = new MessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				IntentMessage message = db.IntentMessages.FirstOrDefault(x => x.Id == id);
				List<IntentMessagesRead> reads = db.IntentMessagesReads.Where(x => x.IntentMessageId == id).ToList();
				db.IntentMessagesReads.RemoveRange(reads);
				db.IntentMessages.Remove(message);
				db.SaveChanges();
				return RedirectToAction("Detail", "Intent", new { id = message.IntentId });
			}
			
		}
		#endregion
	}
}

Alexa.Skill/Views/Intent/Add.cshtml
@model IntentAddViewModel

@{
    ViewBag.Title = "Add";
}

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.SkillId })
}

@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.SkillId })
}


<h1>Intent erstellen</h1>
<hr />

@using (Html.BeginForm("Add", "Intent", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", style = "padding-top:30px;" }))
{
	@Html.HiddenFor(x => x.SkillId)
	<div class="form-group">
		@Html.LabelFor(x => x.ShouldEndSession, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.CheckBoxFor(x => x.ShouldEndSession, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.ShouldEndSession)
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(x => x.Name, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.Name)
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Erstellen</button>
		</div>
	</div>
}

Alexa.Skill/Views/Intent/Detail.cshtml
@using Alexa.Skill.Models.Intents
@model IntentDetailViewModel

@{
    ViewBag.Title = "Detail";
	string borderStyles = "";
}
@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.SkillId })
}
@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.SkillId })
}


<h2>@Model.Name</h2>
<hr />

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success ">
			<div class="panel-heading">Antworten</div>
			@foreach (MessageOverviewItemViewModel message in Model.Messages)
			{
				<div class="panel-body" style="@borderStyles">

					<div class="row">
						<div class="col-md-9">@message.Message</div>
						<div class="col-md-3">
							<div class="row text-right" style="margin:10px 0;">
								<a href="@Url.Action("Edit", "Message", new { id = message.MessageId})" class="btn btn-info">Bearbeiten</a>
								<a href="@Url.Action("DeleteConfirm", "Message", new { id = message.MessageId})" class="btn btn-danger">Löschen</a>
							</div>
						</div>
					</div>
				</div>
				borderStyles = "border-top:1px solid #ddd";
			}
			<div class="panel-body text-right" style="border-top:1px solid #ddd">
				<a href="@Url.Action("Add", "Message", new { id = Model.IntentId})" class="btn btn-success">Neue erstellen</a>
			</div>
		</div>
	</div>
</div>

@{
	borderStyles = "";
}
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success ">
			<div class="panel-heading">User Fragen</div>
			@foreach (KeyValuePair<int, string> intentCall in Model.IntentCalls)
			{
				<div class="panel-body" style="@borderStyles">

					<div class="row">
						<div class="col-md-9">@intentCall.Value</div>
						<div class="col-md-3">
							<div class="row text-right" style="margin:10px 0;">
								<a href="@Url.Action("Edit", "IntentCall", new { id = intentCall.Key})" class="btn btn-info">Bearbeiten</a>
								<a href="@Url.Action("DeleteConfirm", "IntentCall", new { id = intentCall.Key})" class="btn btn-danger">Löschen</a>
							</div>
						</div>
					</div>
				</div>
				borderStyles = "border-top:1px solid #ddd";
			}
			<div class="panel-body text-right" style="border-top:1px solid #ddd">
				<a href="@Url.Action("Add", "IntentCall", new { id = Model.IntentId})" class="btn btn-success">Neue erstellen</a>
			</div>
		</div>
	</div>
</div>

Alexa.Skill/Views/Intent/Edit.cshtml
@model IntentEditViewModel

@{
    ViewBag.Title = "Edit";
}
@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.SkillId })
}
@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.SkillId })
}

<h1>Intent bearbeiten</h1>
<hr />

@using (Html.BeginForm("Edit", "Intent", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", style = "padding-top:30px;" }))
{
	@Html.HiddenFor(x => x.IntentId)
	<div class="form-group">
		@Html.LabelFor(x => x.ShouldEndSession, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.CheckBoxFor(x => x.ShouldEndSession, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.ShouldEndSession)
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(x => x.Name, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.Name)
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Speichern</button>
		</div>
	</div>
}