Alexa.Skill/Models/Home/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Home
{
	public class HomeViewModel
	{
		public List<SkillOverviewItem> Skills { get; set; }

		public HomeViewModel()
		{
			Skills = new List<SkillOverviewItem>();
		}
	}
}

Alexa.Skill/Models/Home/MainMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Home
{
	public class MainMenuViewModel
	{
		public int SkillId { get; set; }

		public Dictionary<int,string> Intents { get; set; }

		public MainMenuViewModel()
		{
			Intents = new Dictionary<int, string>();
		}
	}
}

Alexa.Skill/Models/Home/SkillNameMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Home
{
	public class SkillNameMenuViewModel
	{
		public int SkillId { get; set; }
		public string SkillName { get; set; }
	}
}

Alexa.Skill/Models/Home/SkillOverviewItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Home
{
	public class SkillOverviewItem
	{
		public int Id { get; set; }
		public string Name { get; set; }

		public int UsageCount { get; set; }
		public int UserCount { get; set; }

		public int UsageCount24h { get; set; }
		public int UserCount24h { get; set; }
	}
}

Alexa.Skill/Controllers/HomeController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Home;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Title = "Alex Skill Konfigurator";
			HomeViewModel model = new HomeViewModel();

			string userId = User.Identity.GetUserId();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				List<Context.Skill> skills = db.Skills.Where(x => x.UserId == userId).OrderBy(x => x.Name).ToList();
				if(skills != null)
				{
					foreach (Context.Skill skill in skills)
					{
						List<RequestLog> logs = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).ToList();
						int usageCount = logs.Count();
						int userCount = logs.Select(x => x.UserId).Distinct().Count();
						DateTime yesterday = new DateTime();
						yesterday = DateTime.Now.AddDays(-1);
						int usageCount24h= logs.Where(x => x.RequestTime > yesterday).Count();
						int userCount24h = logs.Where(x => x.RequestTime > yesterday).Select(x => x.UserId).Distinct().Count();

						model.Skills.Add(new SkillOverviewItem()
						{
							Id = skill.Id,
							Name = skill.Name,
							UsageCount = usageCount,
							UserCount = userCount,
							UsageCount24h = usageCount24h,
							UserCount24h = userCount24h
						});
					}
				}
			}
			return View(model);
		}

		public PartialViewResult SkillNameMenu(int skillId)
		{
			SkillNameMenuViewModel model = new SkillNameMenuViewModel()
			{
				SkillId = skillId
			};

			if (skillId == 0)
			{
				return PartialView(model);
			}

			

			string userId = User.Identity.GetUserId();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == skillId && x.UserId == userId);
				if(skill == null)
				{
					return PartialView(model);
				}
				model.SkillName = skill.Name;
			}
			
			return PartialView(model);
		}

		public PartialViewResult MainMenu(int skillId)
		{
			if (skillId == 0)
			{
				return null;
			}

			MainMenuViewModel model = new MainMenuViewModel()
			{
				SkillId = skillId
			};

			string userId = User.Identity.GetUserId();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == skillId && x.UserId == userId);
				if(skill == null)
				{
					return null;
				}
				foreach (Intent intent in skill.Intents.OrderBy(x => x.Name))
				{
					model.Intents.Add(intent.Id, intent.Name);
				}
			}


			return PartialView(model);
		}
	}
}

Alexa.Skill/Controllers/SkillConfigController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.SkillConfig;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class SkillConfigController : Controller
	{
		public ActionResult Index(int id)
		{
			SkillConfigViewModel model = new SkillConfigViewModel()
			{
				SkillId = id
			};
			string intents = "";
			string delimiter = "";
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id);
				if(skill == null)
				{
					return null;
				}
				foreach (Intent intent in skill.Intents.Where(x => x.IntentCalls.Count > 0))
				{
					intents = intents + delimiter + "{\"intent\": \"" + intent.Name + "\"}";
					delimiter = ",";
					foreach (IntentCall intentCall in intent.IntentCalls)
					{
						model.SampleUtterances = model.SampleUtterances + intent.Name + " " + intentCall.CallText + Environment.NewLine;
					};
					
				}
			}
			model.IntentSchema = "{\"intents\": [" + intents + "]}";

			return View(model);
		}
	}
}

Alexa.Skill/Controllers/SkillController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Intents;
using Alexa.Skill.Models.Skills;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class SkillController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add()
		{
			
			SkillAddViewModel model = new SkillAddViewModel()
			{
				SkillTypes = SkillList()
			};
			
			return View(model);
		}

		[HttpPost]
		public ActionResult Add(SkillAddViewModel model)
		{
			string userId = User.Identity.GetUserId();
			if (ModelState.IsValid)
			{
				
				using (AlexaSkillEntities db = new AlexaSkillEntities())
				{
					db.Skills.Add(new Context.Skill()
					{
						ApplicationID = model.ApplicationID,
						Name = model.Name,
						UserId = userId,
						SkillType = model.SkillTypeId
					});
					db.SaveChanges();
					return RedirectToAction("Index", "Home");
				}
			}
			model.SkillTypes = SkillList();
			return View(model);
		}
		#endregion

		#region Detail
		[HttpGet]
		public ActionResult Detail(int id)
		{
			string userId = User.Identity.GetUserId();
			SkillDetailModel model = new SkillDetailModel()
			{
				Id = id
			};

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id && x.UserId == userId);
				if(skill == null)
				{
					return null;
				}
				model.Name = skill.Name;
				model.SkillType = (Enums.SkillType)Enum.ToObject(typeof(Enums.SkillType), skill.SkillType) ;
			}

			return View(model);
		}
		#endregion

		#region Intents
		[HttpGet]
		public ActionResult Intents(int id)
		{
			string userId = User.Identity.GetUserId();
			IntentOverviewViewModel model = new IntentOverviewViewModel()
			{
				SkillId = id
			};
			string skillName;
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id && x.UserId == userId);
				if (skill == null)
				{
					return null;
				}
				skillName = skill.Name;
				List<Intent> intents = db.Intents.Where(x => x.SkillId == skill.Id).ToList();

				foreach (Intent intent in intents)
				{
					model.Intents.Add(new IntentItemViewModel()
					{
						Id = intent.Id,
						Name = intent.Name
					});
				}
			}
			

			return View(model);
		}
		#endregion

		#region WelcomeMessages
		public ActionResult WelcomeMessages(int id)
		{
			SkillWelcomeMessagesOverviewViewModel model = new SkillWelcomeMessagesOverviewViewModel();
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id);
				if (skill == null)
				{
					return null;
				}
				model.SkillId = skill.Id;

				foreach (WelcomeMessage welcomeMessage in skill.WelcomeMessages)
				{
					model.Messages.Add(new Models.Messages.MessageOverviewItemViewModel
					{
						MessageId = welcomeMessage.Id,
						Message = welcomeMessage.Message
					});
				}
			}

			return View(model);
		}
		#endregion

		#region Private Functions
		private List<SelectListItem> SkillList()
		{
			List<SelectListItem> skills = new List<SelectListItem>();
			string userId = User.Identity.GetUserId();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				foreach (SkillType skillType in db.SkillTypes.Where(x => x.UserId == null || x.UserId == userId))
				{
					skills.Add(new SelectListItem()
					{
						Text = skillType.Name,
						Value = skillType.Id.ToString()
					});
				}
			}

			return skills;
		}
		#endregion
	}
}

Alexa.Skill/Controllers/StatisticController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Statistic;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class StatisticController : Controller
	{
		[HttpGet]
		public ActionResult Index(int id)
		{
			StatisitcViewModel model = new StatisitcViewModel()
			{
				SkillId = id
			};

			model.Settings.RequestCounts = 20;

			return Index(model);
		}

		[HttpPost]
		public ActionResult Index(StatisitcViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == model.SkillId);

				List<RequestLog> logs = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).OrderByDescending(x => x.RequestTime).Take(model.Settings.RequestCounts).ToList();

				var chartRequests = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).GroupBy(x => EntityFunctions.TruncateTime(x.RequestTime)).Select(x => new
				{
					Value = x.Count(),
					Day = (DateTime)x.Key
				}).OrderBy(x => x.Day).ToList();

				var allLogs = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).ToList();

				foreach (var chartRequest in chartRequests)
				{
					model.ChartRequests.Add(new ChartPoint() { Value = chartRequest.Value, Date = chartRequest.Day });
					model.ChartUsers.Add(new ChartPoint() { Value = allLogs.Where(x => x.RequestTime.Date == chartRequest.Day.Date).Select(x => x.UserId).Distinct().Count(), Date = chartRequest.Day });
				}
				foreach (RequestLog log in logs)
				{
					model.RequestLogs.Add(new RequestLogViewModel()
					{
						Information = log.Information,
						Intent = log.Intent,
						IntentParam = log.IntentParam,
						RequestTime = log.RequestTime,
						RequestType = log.RequestType,
						UserId = log.UserId
					});
				}
			}
			return View(model);
		}
	}
}

Alexa.Skill/Views/Home/Index.cshtml
@using Alexa.Skill.Models.Home
@model HomeViewModel

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = 0 })
}

<div class="row">
	@foreach (SkillOverviewItem skill in Model.Skills)
	{
		<div class="col-md-4">
			<div class="panel panel-success ">
				<div class="panel-heading">@skill.Name</div>
				<div class="panel-body">
					Gesamt:
					<div class="row">
						<div class="col-md-3 col-xs-3"><strong>Aufrufe:</strong></div><div class="col-md-3 col-xs-3">@skill.UsageCount</div>
						<div class="col-md-3 col-xs-3"><strong>User:</strong></div><div class="col-md-3 col-xs-3">@skill.UserCount</div>
					</div>
					<hr />
					Letzte 24h:
					<div class="row">
						<div class="col-md-3 col-xs-3"><strong>Aufrufe:</strong></div><div class="col-md-3 col-xs-3">@skill.UsageCount24h</div>
						<div class="col-md-3 col-xs-3"><strong>User:</strong></div><div class="col-md-3 col-xs-3">@skill.UserCount24h</div>
					</div>
				</div>
				<div class="panel-body text-right" style="border-top:1px solid #ddd">
					<a href="@Url.Action("Detail", "Skill", new { id = skill.Id})" class="btn btn-success">Bearbeiten</a>
				</div>
			</div>
		</div>
	}
	

	<div class="col-md-4">
		<div class="panel panel-info ">
			<div class="panel-heading">Skill erstellen</div>
			<a href="@Url.Action("Add","Skill")">
				<div class="panel-body text-center" style="font-size:50px;">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				</div>
			</a>
		</div>
	</div>
</div>

Alexa.Skill/Views/Home/MainMenu.cshtml
@model MainMenuViewModel

<li>@Html.ActionLink("Skill Übersicht", "Index", "Home")</li>

<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Intents <span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li>@Html.ActionLink("Übersicht", "Intents", "Skill", new { id = Model.SkillId }, null)</li>
		<li role="separator" class="divider"></li>
		@foreach (KeyValuePair<int, string> intent in Model.Intents)
		{
			<li>@Html.ActionLink(intent.Value, "Detail", "Intent", new { id = intent.Key }, null)</li>
		}
	</ul>
</li>

<li>@Html.ActionLink("Welcome Messages", "WelcomeMessages", "Skill", new { id = Model.SkillId }, null)</li>
<li>@Html.ActionLink("Statistik", "Index", "Statistic", new { id = Model.SkillId }, null)</li>
<li>@Html.ActionLink("Konfig", "Index", "SkillConfig", new { id = Model.SkillId }, null)</li>

Alexa.Skill/Views/Home/SkillNameMenu.cshtml
@model SkillNameMenuViewModel

@if (String.IsNullOrEmpty(Model.SkillName))
{
	@Html.ActionLink("Alexa Skills", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
}
else
{
	@Html.ActionLink(Model.SkillName, "Detail", "Skill", new { id = Model.SkillId }, new { @class = "navbar-brand" })
}