Alexa.Skill/Models/Intents/IntentAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentAddViewModel
	{
		[Display(Name = "Session beenden?")]
		public bool ShouldEndSession { get; set; }
		public int SkillId { get; set; }
		[Display(Name = "Intent Name")]
		public string Name { get; set; }

		public IntentAddViewModel()
		{
			ShouldEndSession = true;
		}
	}
}

Alexa.Skill/Models/Intents/IntentDetailViewModel.cs
using Alexa.Skill.Models.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentDetailViewModel
	{
		public int IntentId { get; set; }
		public string Name { get; set; }
		public int SkillId { get; set; }
		public string SkillName { get; set; }

		public List<MessageOverviewItemViewModel> Messages { get; set; }

		public Dictionary<int, string> IntentCalls { get; set; }

		public IntentDetailViewModel()
		{
			Messages = new List<MessageOverviewItemViewModel>();
			IntentCalls = new Dictionary<int, string>();
		}
	}
}

Alexa.Skill/Models/Intents/IntentEditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentEditViewModel
	{
		[Display(Name = "Session beenden?")]
		public bool ShouldEndSession { get; set; }
		public int IntentId { get; set; }
		[Display(Name = "Intent Name")]
		public string Name { get; set; }

		public int SkillId { get; set; }
		public IntentEditViewModel()
		{
			ShouldEndSession = true;
		}
	}
}

Alexa.Skill/Models/Intents/IntentItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Models.Intents
{
	public class IntentItemViewModel
	{
		public int Id { get; set; }

		[AllowHtml]
		public string Name { get; set; }
	}
}

Alexa.Skill/Models/Intents/IntentMessagesOverviewViewModel.cs
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;

namespace Alexa.Skill.Models.Intents
{
	public class IntentMessagesOverviewViewModel
	{
		public int IntentId { get; set; }
		public string IntentName { get; set; }
		public string SkillName { get; set; }

		public List<MessageOverviewItemViewModel> Messages { get; set; }

		public IntentMessagesOverviewViewModel()
		{
			Messages = new List<MessageOverviewItemViewModel>();
		}
	}
}

Alexa.Skill/Models/Intents/IntentOverviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alexa.Skill.Models.Intents
{
	public class IntentOverviewViewModel
	{
		public int SkillId { get; set; }
		public List<IntentItemViewModel> Intents { get; set; }

		public IntentOverviewViewModel()
		{
			Intents = new List<IntentItemViewModel>();
		}
	}
}

Alexa.Skill/Models/Skills/SkillAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Models.Skills
{
	public class SkillAddViewModel
	{
		public int Id { get; set; }

		[Required]
		public string Name { get; set; }

		[Required]
		[Display(Name = "Skill ID")]
		public string ApplicationID { get; set; }

		[Required]
		public int SkillTypeId { get; set; }

		[Display(Name = "Skill Arten")]
		public IEnumerable<SelectListItem> SkillTypes { get; set; }

		public SkillAddViewModel()
		{
			SkillTypes = new List<SelectListItem>();

		}
	}
}

Alexa.Skill/Models/Skills/SkillDetailModel.cs
namespace Alexa.Skill.Models.Skills
{
	public class SkillDetailModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public Enums.SkillType SkillType { get; set; }
	}
}

Alexa.Skill/Models/Skills/SkillWelcomeMessagesOverviewViewModel.cs
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;

namespace Alexa.Skill.Models.Intents
{
	public class SkillWelcomeMessagesOverviewViewModel
	{
		public int SkillId { get; set; }

		public List<MessageOverviewItemViewModel> Messages { get; set; }

		public SkillWelcomeMessagesOverviewViewModel()
		{
			Messages = new List<MessageOverviewItemViewModel>();
		}
	}
}

Alexa.Skill/Controllers/IntentController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Intents;
using Alexa.Skill.Models.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class IntentController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add(int id)
		{
			IntentAddViewModel model = new IntentAddViewModel()
			{
				SkillId = id
			};


			return View(model);
		}

		[HttpPost]
		public ActionResult Add(IntentAddViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = new Intent()
				{
					SkillId = model.SkillId,
					Name = model.Name.Replace(" ",""),
					ShouldEndSession = model.ShouldEndSession
				};
				db.Intents.Add(intent);
				db.SaveChanges();
				return RedirectToAction("Detail", "Intent", new { id = intent.Id});
			}
		}
		#endregion

		#region Edit
		[HttpGet]
		public ActionResult Edit(int id)
		{
			IntentEditViewModel model = new IntentEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if(intent != null)
				{
					model.IntentId = intent.Id;
					model.Name = intent.Name;
					model.SkillId = intent.SkillId;
					model.ShouldEndSession = intent.ShouldEndSession;
				}
			}
			


			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(IntentEditViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{

				Intent intent = db.Intents.FirstOrDefault(x => x.Id == model.IntentId);
				if (intent != null)
				{
					intent.Name = model.Name;
					intent.ShouldEndSession = model.ShouldEndSession;
				}
				db.SaveChanges();
				return RedirectToAction("Intents", "Skill", new { id = intent.SkillId });
			}
		}
		#endregion

		#region Detail
		public ActionResult Detail(int id)
		{
			IntentDetailViewModel model = new IntentDetailViewModel();
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Intent intent = db.Intents.FirstOrDefault(x => x.Id == id);
				if(intent == null)
				{
					return null;
				}
				
				model.IntentId = id;
				model.Name = intent.Name;
				model.SkillId = intent.Skill.Id;
				model.SkillName = intent.Skill.Name;

				foreach (IntentMessage message in intent.IntentMessages)
				{
					model.Messages.Add(new MessageOverviewItemViewModel()
					{
						MessageId = message.Id,
						Message = message.Message
					});
				}

				foreach (IntentCall intentCall in intent.IntentCalls)
				{
					model.IntentCalls.Add(intentCall.Id, intentCall.CallText);
				}
			}

			return View(model);
		}
		#endregion
	}
}

Alexa.Skill/Controllers/SkillConfigController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.SkillConfig;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class SkillConfigController : Controller
	{
		public ActionResult Index(int id)
		{
			SkillConfigViewModel model = new SkillConfigViewModel()
			{
				SkillId = id
			};
			string intents = "";
			string delimiter = "";
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id);
				if(skill == null)
				{
					return null;
				}
				foreach (Intent intent in skill.Intents.Where(x => x.IntentCalls.Count > 0))
				{
					intents = intents + delimiter + "{\"intent\": \"" + intent.Name + "\"}";
					delimiter = ",";
					foreach (IntentCall intentCall in intent.IntentCalls)
					{
						model.SampleUtterances = model.SampleUtterances + intent.Name + " " + intentCall.CallText + Environment.NewLine;
					};
					
				}
			}
			model.IntentSchema = "{\"intents\": [" + intents + "]}";

			return View(model);
		}
	}
}

Alexa.Skill/Controllers/SkillController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Intents;
using Alexa.Skill.Models.Skills;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class SkillController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add()
		{
			
			SkillAddViewModel model = new SkillAddViewModel()
			{
				SkillTypes = SkillList()
			};
			
			return View(model);
		}

		[HttpPost]
		public ActionResult Add(SkillAddViewModel model)
		{
			string userId = User.Identity.GetUserId();
			if (ModelState.IsValid)
			{
				
				using (AlexaSkillEntities db = new AlexaSkillEntities())
				{
					db.Skills.Add(new Context.Skill()
					{
						ApplicationID = model.ApplicationID,
						Name = model.Name,
						UserId = userId,
						SkillType = model.SkillTypeId
					});
					db.SaveChanges();
					return RedirectToAction("Index", "Home");
				}
			}
			model.SkillTypes = SkillList();
			return View(model);
		}
		#endregion

		#region Detail
		[HttpGet]
		public ActionResult Detail(int id)
		{
			string userId = User.Identity.GetUserId();
			SkillDetailModel model = new SkillDetailModel()
			{
				Id = id
			};

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id && x.UserId == userId);
				if(skill == null)
				{
					return null;
				}
				model.Name = skill.Name;
				model.SkillType = (Enums.SkillType)Enum.ToObject(typeof(Enums.SkillType), skill.SkillType) ;
			}

			return View(model);
		}
		#endregion

		#region Intents
		[HttpGet]
		public ActionResult Intents(int id)
		{
			string userId = User.Identity.GetUserId();
			IntentOverviewViewModel model = new IntentOverviewViewModel()
			{
				SkillId = id
			};
			string skillName;
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id && x.UserId == userId);
				if (skill == null)
				{
					return null;
				}
				skillName = skill.Name;
				List<Intent> intents = db.Intents.Where(x => x.SkillId == skill.Id).ToList();

				foreach (Intent intent in intents)
				{
					model.Intents.Add(new IntentItemViewModel()
					{
						Id = intent.Id,
						Name = intent.Name
					});
				}
			}
			

			return View(model);
		}
		#endregion

		#region WelcomeMessages
		public ActionResult WelcomeMessages(int id)
		{
			SkillWelcomeMessagesOverviewViewModel model = new SkillWelcomeMessagesOverviewViewModel();
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == id);
				if (skill == null)
				{
					return null;
				}
				model.SkillId = skill.Id;

				foreach (WelcomeMessage welcomeMessage in skill.WelcomeMessages)
				{
					model.Messages.Add(new Models.Messages.MessageOverviewItemViewModel
					{
						MessageId = welcomeMessage.Id,
						Message = welcomeMessage.Message
					});
				}
			}

			return View(model);
		}
		#endregion

		#region Private Functions
		private List<SelectListItem> SkillList()
		{
			List<SelectListItem> skills = new List<SelectListItem>();
			string userId = User.Identity.GetUserId();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				foreach (SkillType skillType in db.SkillTypes.Where(x => x.UserId == null || x.UserId == userId))
				{
					skills.Add(new SelectListItem()
					{
						Text = skillType.Name,
						Value = skillType.Id.ToString()
					});
				}
			}

			return skills;
		}
		#endregion
	}
}

Alexa.Skill/Controllers/StatisticController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Statistic;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class StatisticController : Controller
	{
		[HttpGet]
		public ActionResult Index(int id)
		{
			StatisitcViewModel model = new StatisitcViewModel()
			{
				SkillId = id
			};

			model.Settings.RequestCounts = 20;

			return Index(model);
		}

		[HttpPost]
		public ActionResult Index(StatisitcViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				Context.Skill skill = db.Skills.FirstOrDefault(x => x.Id == model.SkillId);

				List<RequestLog> logs = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).OrderByDescending(x => x.RequestTime).Take(model.Settings.RequestCounts).ToList();

				var chartRequests = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).GroupBy(x => EntityFunctions.TruncateTime(x.RequestTime)).Select(x => new
				{
					Value = x.Count(),
					Day = (DateTime)x.Key
				}).OrderBy(x => x.Day).ToList();

				var allLogs = db.RequestLogs.Where(x => x.ApplicationId == skill.ApplicationID).ToList();

				foreach (var chartRequest in chartRequests)
				{
					model.ChartRequests.Add(new ChartPoint() { Value = chartRequest.Value, Date = chartRequest.Day });
					model.ChartUsers.Add(new ChartPoint() { Value = allLogs.Where(x => x.RequestTime.Date == chartRequest.Day.Date).Select(x => x.UserId).Distinct().Count(), Date = chartRequest.Day });
				}
				foreach (RequestLog log in logs)
				{
					model.RequestLogs.Add(new RequestLogViewModel()
					{
						Information = log.Information,
						Intent = log.Intent,
						IntentParam = log.IntentParam,
						RequestTime = log.RequestTime,
						RequestType = log.RequestType,
						UserId = log.UserId
					});
				}
			}
			return View(model);
		}
	}
}

Alexa.Skill/Controllers/WelcomeMessageController.cs
using Alexa.Skill.Context;
using Alexa.Skill.Models.Messages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Alexa.Skill.Controllers
{
	public class WelcomeMessageController : Controller
	{
		#region Add
		[HttpGet]
		public ActionResult Add(int id)
		{
			WelcomeMessageEditViewModel model = new WelcomeMessageEditViewModel()
			{
				SkillId = id
			};
			return View("Edit", model);
		}
		#endregion

		#region Edit
		[HttpGet]
		public ActionResult Edit(int id)
		{
			WelcomeMessageEditViewModel model = new WelcomeMessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				WelcomeMessage message = db.WelcomeMessages.FirstOrDefault(x => x.Id == id);
				if (message != null)
				{
					model.MessageId = message.Id;
					model.Message = message.Message;
					model.SkillId = message.SkillId;
				}
			}
			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(WelcomeMessageEditViewModel model)
		{
			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				if(model.MessageId != 0)
				{
					WelcomeMessage message = db.WelcomeMessages.FirstOrDefault(x => x.Id == model.MessageId);
					if (message != null)
					{
						message.Message = model.Message;
					}
				}
				else
				{
					WelcomeMessage message = new WelcomeMessage()
					{
						Message = model.Message,
						SkillId = model.SkillId
					};
					db.WelcomeMessages.Add(message);
				}
				db.SaveChanges();

			}
			return RedirectToAction("WelcomeMessages", "Skill", new { id = model.SkillId });
		}
		#endregion

		#region Delete
		[HttpGet]
		public ActionResult DeleteConfirm(int id)
		{
			WelcomeMessageEditViewModel model = new WelcomeMessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				WelcomeMessage message = db.WelcomeMessages.FirstOrDefault(x => x.Id == id);
				if (message != null)
				{
					model.MessageId = message.Id;
					model.Message = message.Message;
					model.SkillId = message.SkillId;
				}
			}
			return View(model);
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			WelcomeMessageEditViewModel model = new WelcomeMessageEditViewModel();

			using (AlexaSkillEntities db = new AlexaSkillEntities())
			{
				WelcomeMessage message = db.WelcomeMessages.FirstOrDefault(x => x.Id == id);
				List<WelcomeMessagesRead> reads = db.WelcomeMessagesReads.Where(x => x.WelcomeMessageId == id).ToList();
				db.WelcomeMessagesReads.RemoveRange(reads);
				db.WelcomeMessages.Remove(message);
				db.SaveChanges();
				return RedirectToAction("WelcomeMessages", "Skill", new { id = message.SkillId });
			}
			
		}
		#endregion
	}
}

Alexa.Skill/Views/Skill/Add.cshtml
@using Alexa.Skill.Models.Skills
@model SkillAddViewModel
@{
	ViewBag.Title = "Skill erstellen";
}

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = 0 })
}

<h2>Skill erstellen</h2>
<hr />
@using (Html.BeginForm("Add", "Skill", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", style = "padding-top:30px;" }))
{
	
	<div class="form-group">
		@Html.LabelFor(x => x.SkillTypes, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.DropDownListFor(model => model.SkillTypeId, Model.SkillTypes, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.Name)
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(x => x.Name, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.Name)
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(x => x.ApplicationID, new { @class = "col-sm-2 control-label" })
		<div class="col-sm-10">
			@Html.TextBoxFor(x => x.ApplicationID, new { @class = "form-control" })
			@Html.ValidationMessageFor(x => x.ApplicationID)
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">erstellen</button>
		</div>
	</div>
}

Alexa.Skill/Views/Skill/Detail.cshtml
@using Alexa.Skill.Models.Skills
@model SkillDetailModel
@{
    ViewBag.Title = "Detail";
}

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.Id })
}
@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.Id })
}

@switch (Model.SkillType)
{
	case SkillType.InformationSkill:
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Intents</h2></div>
					<div class="panel-body">
						Hier kannst du die Intents von deinem Skill bearbeiten
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("Intents", "Skill", new { id = Model.Id})" class="btn btn-success">Bearbeiten</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Welcome Message</h2></div>
					<div class="panel-body">
						Hier kannst du die Welcome Message von deinem Skill bearbeiten
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("WelcomeMessages", "Skill", new { id = Model.Id})" class="btn btn-success">Bearbeiten</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Statistiken</h2></div>
					<div class="panel-body">
						Hier kannst du die Statistiken von deinem Skill sehen
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("Index", "Statistic", new { id = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Konfigurationen</h2></div>
					<div class="panel-body">

					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("Index", "SkillConfig", new { id = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
		</div>
		break;
	case SkillType.CoreTemperature:
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Kerntemperaturen</h2></div>
					<div class="panel-body">
						Hier kannst du die Kerntemperaturen von deinem Skill sehen
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("Overview", "CoreTemperature", new { skillId = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Antworten</h2></div>
					<div class="panel-body">
						Hier kannst du die Antworten von deinem Skill sehen
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("AnswerOverview", "CoreTemperature", new { skillId = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Aufrufe</h2></div>
					<div class="panel-body">
						Hier kannst du die Aufrufe von deinem Skill sehen
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("UserCallOverview", "CoreTemperature", new { skillId = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-success ">
					<div class="panel-heading text-center"><h2>Statistiken</h2></div>
					<div class="panel-body">
						Hier kannst du die Statistiken von deinem Skill sehen
					</div>
					<div class="panel-body text-right" style="border-top:1px solid #ddd">
						<a href="@Url.Action("Index", "Statistic", new { id = Model.Id})" class="btn btn-success">Anzeigen</a>
					</div>
				</div>
			</div>
		</div>
		break;
}

Alexa.Skill/Views/Skill/Intents.cshtml
@using Alexa.Skill.Models.Intents
@model IntentOverviewViewModel

@{
    ViewBag.Title = "Intents";
}

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.SkillId })
}
@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.SkillId })
}

<h2>Intents</h2>
<hr />
<div class="row">
	@foreach (IntentItemViewModel intent in Model.Intents)
	{
		<div class="col-md-4">
			<div class="panel panel-success ">
				<div class="panel-heading"><strong>@intent.Name</strong></div>
				<div class="panel-body text-right" style="border-top:1px solid #ddd">
					<a href="@Url.Action("Detail", "Intent", new { id = intent.Id})" class="btn btn-success">Details</a>
					<a href="@Url.Action("Edit", "Intent", new { id = intent.Id})" class="btn btn-default">Bearbeiten</a>
				</div>
			</div>
		</div>
	}

	<div class="col-md-4">
		<div class="panel panel-info ">
			<div class="panel-heading">Intent erstellen</div>
			<a href="@Url.Action("Add","Intent", new { id = Model.SkillId})">
				<div class="panel-body text-center" style="font-size:50px;">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				</div>
			</a>
		</div>
	</div>
</div>

Alexa.Skill/Views/Skill/WelcomeMessages.cshtml
@model SkillWelcomeMessagesOverviewViewModel

@{
	ViewBag.Title = "Welcome Messages";
	string borderStyles = "";
}

@section SkillNameMenu{
	@Html.Action("SkillNameMenu", "Home", new { skillId = Model.SkillId })
}
@section MainMenu{
	@Html.Action("MainMenu", "Home", new { skillId = Model.SkillId })
}

<h2>Welcome Messages</h2>

<hr />
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success ">
			<div class="panel-heading">Mitteilungen</div>
			@foreach (MessageOverviewItemViewModel message in Model.Messages)
			{
				<div class="panel-body" style="@borderStyles">

					<div class="row">
						<div class="col-md-9">@message.Message</div>
						<div class="col-md-3">
							<div class="row text-right" style="margin:10px 0;">
								<a href="@Url.Action("Edit", "WelcomeMessage", new { id = message.MessageId})" class="btn btn-info">Bearbeiten</a>
								<a href="@Url.Action("DeleteConfirm", "WelcomeMessage", new { id = message.MessageId})" class="btn btn-danger">Löschen</a>
							</div>
						</div>
					</div>
				</div>
				borderStyles = "border-top:1px solid #ddd";
			}
			<div class="panel-body text-right" style="border-top:1px solid #ddd">
				<a href="@Url.Action("Add", "WelcomeMessage", new { id = Model.SkillId})" class="btn btn-success">Neue erstellen</a>
			</div>
		</div>
	</div>
</div>